namespace: hearthminion
name: hearthminion
version: 0.2.0

description: Installs home automation and entertainment software on your network

readme: "README.md"
license_file: "LICENSE.md"
tags: []

dependencies:
  - bloodymage.rebeldream

repository: https://github.com/hearthminion/ansible-collection-hearthminion
documentation: http://docs.hearthminion.com
homepage: https://hearthminion.com
issues: https://github.com/hearthminion/ansible-collection-hearthminion/issues

build_ignore: []

authors:
- G Derber <gd.github@hearthminion.com>
