---
# defaults file for homeassistant
packages:
  - libxml2-dev
  - libxslt1-dev
  - zlib1g-dev

homeassistant_config_dir: "/usr/share/hassio/homeassistant"
homeassistant_config_files:
  - name: secrets
    mode: "0644"

homeassistant_caldav: no
