---
# defaults file for mythtv
packages:
  - mythtv-backend
  - libmyth-python
  - libmythtv-perl

mythtv_db_server: "{{ groups['mysql_compatible_servers'][0] }}"
mythtv_db_name: "mythconverg"
mythtv_db_user: "mythtv"
mythtv_db_password: "password"

