- name: Print Variables
  debug:
    msg:
      - "Game: {{ game.name }}"
      - "Full Name: {{ game.full_name }}"
      - "Installer Directory: {{ installer_dir }}/{{ game.name}}/"
      - "Installer: {{ installer_dir }}/{{ game.name }}/{{ game.installer }}"
      - "User: {{ game_user }}"
    verbosity: 2
  tags:
    - install-games

- name: "Installing '{{ game.full_name}}'"
  script:
    cmd: "{{ installer_dir }}/{{ game.name }}/{{ game.installer }} -- --i-agree-to-all-licenses --noreadme --nooptions --noprompt --destination /home/{{ game_user }}/RetroPie/roms/ports/.games/{{ game.name }}"
    creates: "/home/{{ game_user }}/RetroPie/roms/ports/.games/{{ game.name }}/start.sh"
  become: yes
  become_user: "{{ game_user }}"
  tags:
    - install-games

- name: "Create '{{ game.full_name }}' Starter Script"
  template:
    src: "{{ role_path }}/templates/gog_starter_script.j2"
    dest: "/home/{{ game_user }}/RetroPie/roms/ports/{{ game.full_name }}.sh"
    mode: "0755"
  become: yes
  become_user: "{{ game_user }}"
  tags:
    - install-games

- name: "Clean-Up the Desktop"
  file:
    path: "/home/{{ game_user }}/Desktop/{{ item }}"
    state: absent
  loop: "{{ game.desktop_files }}"
  tags:
    - install-games
