- name: "Install {{ item.name }}"
  script:
    cmd: "{{ installer_dir }}/{{ item.name }}/{{ item.file }} -- --i-agree-to-all-licenses --noreadme --nooptions --noprompt --destination /home/{{ game_user }}/RetroPie/roms/ports/.games/{{ item.name }}"
    chdir: /tmp
    creates: "/home/{{ game_user }}/RetroPie/roms/ports/.games/{{ item.name }}/start.sh"
  become: yes
  become_user: "{{ game_user }}"

- name: Setup Starter Script
  template:
    src: "{{ role_path }}/templates/starter_script.j2"
    dest: "/home/{{ game_user }}/RetroPie/roms/ports/{{ item.full_name }}.sh"
    mode: "0755"
  become: yes
  become_user: "{{ game_user }}"
