---
# defaults file for mythtv
hearthminion_mythtv_packages:
  - libmyth-python
  - libmythtv-perl

hearthminion_mythtv_backend_packages:
  - mythtv-backend

hearthminion_mythtv_frontend_packages:
  - mythtv-frontend
  - mytharchive
  - mythbrowser
  - mythweather
  - mythgame
  - mythnews
  - mythmusic


hearthminion_mythtv_db_server: "{{ groups['mysql_compatible_servers'][0] }}"
hearthminion_mythtv_db_name: "mythconverg"
hearthminion_mythtv_db_user: "mythtv"
hearthminion_mythtv_db_password: "password"

hearthminion_mythtv_system_user: "mythtv"

hearthminion_mythtv_streaming_services:
  - name: "amazon"
    text: "Watch Amazon Prime Video"
    action: "EXEC /home/mythtv/.local/bin/amazon"
    app: "https://smile.amazon.com/Prime-Video/b?node=2676882011"
    fullscreen: yes
  - name: "disney"
    text: "Watch Disney+"
    action: "EXEC /home/mythtv/.local/bin/disney"
    app: "https://disneyplus.com"
    fullscreen: yes
  - name: locast
    text: "Watch Locast"
    action: "EXEC /home/mythtv/.local/bin/locast"
    app: "https://www.locast.org"
    fullscreen: yes
  - name: "netflix"
    text: "Watch Netflix"
    action: "EXEC /home/mythtv/.local/bin/netflix"
    app: "https://netflix.com"
    fullscreen: yes
  - name: "vudu"
    text: "Watch Vudu"
    action: "EXEC /home/mythtv/.local/bin/vudu"
    app: "https://www.vudu.com"
    fullscreen: yes
  - name: "youtube"
    text: "Watch YouTube"
    action: "EXEC /home/mythtv/.local/bin/youtube"
    app: "https://www.youtube.com"
  - name: "mythtv-browser"
    text: "Internet Browser"
    action: "EXEC /home/mythtv/.local/bin/mythtv-browser"

hearthminion_mythtv_chrome_user_data_dir: "/home/{{ hearthminion_mythtv_system_user }}/.config/chrome-mythtv"
