---
# defaults file for config_defaults
hearthminion_hostname: "{{ ansible_hostname_short }}"
hearthminion_fqdn: "{{ ansible_fqdn }}"

# ==================================================================================================
#
#
#
# ==================================================================================================
__os_variables_files:
  - "{{ __network_os }}.yml"
  - "{{ __lsb_id | lower }}.yml"
  - "{{ __distribution | lower }}.yml"
  - "{{ __distribution_short | lower }}.yml"
  - "{{ __os_family | lower }}_family.yml"
  - "{{ __system | lower }}.yml"
  - main.yml
