galaxy_info:
  author: G Derber
  description: All handlers used throughout the collection
  company: Bloodymage

  issue_tracker_url: http://github.com/hearthminion/ansible-collection-hearthminion

  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Rasbian
      versions:
        - 10
    - name: Debian
      versions:
        - 10
    - name: Ubuntu
      versions:
        - 18.04

  galaxy_tags:
    - bloodymage
    - collection
    - handlers

dependencies:
  - role: hearthminion.hearthminion.config_defaults
  - role: hearthminion.hearthminion.collection_handlers
