---
# tasks file for mythtv_frontend
# ======================================================================
#
# Tasks:
#  
#
# ======================================================================
- name: "Pre-tasks"
  block:
    - name: Include OS-specific variables.
      include_vars: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files: "{{ __os_variables_files }}"
          paths:
            - "vars"
      become: no

    - name: "Install packages"
      ansible.builtin.package:
        name: "{{ hearthminion_packages }}"
        state: present
      become: yes


- name: "Install config file"
  ansible.builtin.template:
    src: "config_xml.j2"
    dest: "/etc/mythtv/config.xml"
    owner: "root"
    group: "root"
    mode: "0644"
  become: yes

