---
# tasks file for mythtv_frontend
# ======================================================================
#
# Tasks:
#  
#
# ======================================================================
- name: "Pre-tasks"
  block:
    - name: Include OS-specific variables.
      include_vars: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files: "{{ __os_variables_files }}"
          paths:
            - "vars"
      become: no
      tags:
        - mythtv_backend
        - mythtv-backend
        - mythtv_backend_debug
        - mythtv-backend-debug
        - install-packages

    - name: "Install packages"
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
      become: yes
      tags:
        - mythtv_backend
        - mythtv-backend
        - mythtv_backend_debug
        - mythtv-backend-debug
        - install-packages

- name: "Ensure we have a password for the nextcloud ldap lookup user"
  ansible.builtin.set_fact:
    mythtv_db_password: "{{ lookup('community.general.passwordstore', __password_lookup) }}"
  vars:
    __password_store_id: "{{ hearthminion_domain }}/services/mysql/{{ mythtv_db_user }}"
    __password_length: "length={{ hearthminion_password_length }}"
    __password_overwrite: "overwrite={{ hearthminion_overwrite_password }} backup=yes"
    __password_create: "create=true"
    __password_symbols: "nosymbols=true"
    __password_lookup: "{{ __password_store_id }} {{ __password_create }} {{ __password_length }} {{ __password_symbols }} {{ __password_overwrite }}"
  delegate_to: localhost
  when:
    - mythtv_db_password == "password"
  tags:
    - mythtv_backend
    - mythtv-backend
    - mythtv_backend_debug
    - mythtv-backend-debug

- name: "Install config file"
  ansible.builtin.template:
    src: "config_xml.j2"
    dest: "/etc/mythtv/config.xml"
    owner: "root"
    group: "root"
    mode: "0644"
  become: yes
  tags:
        - mythtv_backend
        - mythtv-backend
        - mythtv_backend_debug
        - mythtv-backend-debug

# ==================================================================================================
#
# Next steps:
# - Ensure user is part of "video" group
# - Is it possible to configure mythtv via cli and mysql inserts?
#
# ==================================================================================================
