- name: Print Variables
  debug:
    msg:
      - "Game: {{ game.name }}"
      - "Full Name: {{ game.full_name }}"
      - "User: {{ game_user }}"
    verbosity: 2
  tags:
    - install-games

- name: "Checkout My eduke32 bugfixes branch"
  command: "git checkout bugfix/eduke32"
  args:
    chdir: "/home/{{ game_user }}/RetroPie-Setup"
  become: yes
  become_user: "{{ game_user }}"
  tags:
    - install-games

- name: "Install {{ game.name }}"
  command: "sudo retropie_packages.sh eduke32 {{ item }}"
  loop: "{{ game.retropie_commands }}"
  become: yes
  become_user: "{{ game_user }}"
  tags:
    - install-games

- name: "Return to development branch"
  command: "git checkout develop"
  args:
    chdir: "/home/{{ game_user }}/RetroPie-Setup"
  become: yes
  become_user: "{{ game_user }}"
  tags:
    - install-games

# ======================================================================
#
# Extract Game
#
# Needs to use steamcmd to install game
#
# ======================================================================
- name: Find Installer
  find:
    path: "{{ installer_dir }}/{{ game.name }}/_atomic_edition"
    pattern: "*{{ game.name }}_*.sh"
  register: installer
  when:
    - game.data_source == "gog"
  tags:
    - install-games

- name: "Extract {{ game.name }}"
  script:
    cmd: "{{ installer_dir }}/{{ game.name }}_atomic_edition/{{ installer }} -- --i-agree-to-all-licenses --noreadme --nooptions --noprompt --destination /tmp/{{ game.name }}"
  become: yes
  become_user: "{{ game_user }}"
  when:
    - game.data_source == "gog"
  tags:
    - install-games

- name: "Install Data Files"
  copy:
    src: "/tmp/{{ game.name }}/data/{{ item }}"
    dest: "/home/{{ game_user }}/RetroPie/roms/ports/duke3d/{{ item | lower }}"
    mode: "0644"
    remote_src: yes
  become: yes
  become_user: "{{ game_user }}"
  loop: "{{ game.gog_data_files }}"
  when:
    - game.data_source == "gog"
  tags:
    - install-games

- name: "Install Data Files"
  copy:
    src: "/home/{{ game_user }}/.steam/steam/steamapps/common/Duke Nukem 3D/gameroot/{{ item }}"
    dest: "/home/{{ game_user }}/RetroPie/roms/ports/duke3d/{{ item | replace('addon/', '') | lower }}"
    mode: "0644"
    remote_src: yes
  become: yes
  become_user: "{{ game_user }}"
  loop: "{{ game.steam_data_files }}"
  when:
    - game.data_source == "steam"
  tags:
    - install-games

- name: Find Uninstaller
  find:
    path: "/tmp/{{ game.name }}/"
    pattern: uninstall_*.sh
  register: uninstaller
  when:
    - game.data_source == "gog"
  tags:
    - install-games

- name: "Remove temporary files"
  command: "/tmp/{{ game.name }}/{{ uninstaller }} --force"
  become: yes
  become_user: "{{ game_user }}"
  ignore_errors: True
  when:
    - game.data_source == "gog"
  tags:
    - install-games

- name: "Ensure temporary files are gone"
  file:
    path: "/tmp/{{ game.name }}"
    state: absent
  tags:
    - install-games
