---
- name: "Create Hue Groups."
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/clip/v2/resource/{{ item['group_definiton']['type'] | lower }}"
    method: POST
    headers:
      hue-application-key: "{{ hearthminion_hue_username }}"
    body: "{{ item['group_definiton'] | to_json }}"
    ca_path: "{{ role_path }}/files/hue.crt"
    validate_certs: false
    body_format: json
  loop: "{{ hearthminion_hue_groups }}"
  become: false
  delegate_to: localhost
  when:
    - hearthminion_hue_groups is truthy
    - item['group_definiton'] is defined
    - item['id'] is not defined
  tags:
    - hue
    - hue-groups

- name: "Update Hue Groups."
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/clip/v2/resource/{{ item['group_definiton']['type'] | lower }}/{{ item['id'] }}"
    method: PUT
    headers:
      hue-application-key: "{{ hearthminion_hue_username }}"
    body: "{{ item['group_definiton'] | to_json }}"
    ca_path: "{{ role_path }}/files/hue.crt"
    validate_certs: false
    body_format: json
  loop: "{{ hearthminion_hue_groups }}"
  become: false
  delegate_to: localhost
  when:
    - hearthminion_hue_groups is truthy
    - item['group_definiton'] is defined
    - item['id'] is defined
  tags:
    - hue
    - hue-groups
