---
# ==================================================================================================
#
# Use API v1 since API v2 does not allow adding lights by serial number.
#
# ==================================================================================================
- name: "Add Hue Lights."
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/{{ hearthminion_hue_username }}/lights"
    method: POST
    body: "{{ serial_number | to_json }}"
    ca_path: "{{ role_path }}/files/hue.crt"
    validate_certs: false
    body_format: json
  loop: "{{ hearthminion_hue_lights }}"
  delegate_to: localhost
  become: no
  vars:
    serial_number:
      deviceid: "{{ item.serial_number }}"
  when:
    - hearthminion_hue_lights is truthy
    - item.serial_number is defined
    - item.serial_number is truthy
    - item.id is not defined
  tags:
    - hue
    - hue-lights

- name: "Update Hue Lights."
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/clip/v2/resource/light/{{ item.id }}"
    method: PUT
    headers:
      hue-application-key: "{{ hearthminion_hue_username }}"
    body: "{{ light_definition | to_json }}"
    ca_path: "{{ role_path }}/files/hue.crt"
    validate_certs: false
    body_format: json
  loop: "{{ hearthminion_hue_lights }}"
  become: false
  delegate_to: localhost
  vars:
    light_definition:
      metadata:
        name: "{{ item.name }}"
      # powerup: {{ hearthminion_hue_power_on_behavior }}"
  when:
    - hearthminion_hue_lights is truthy
    - item.name is defined
    - item.id is defined
  tags:
    - hue
    - hue-lights

- name: "Update Home Assistant Light Entity IDs."
  ansible.builtin.uri:
    url: "http://{{ homeassistant_host }}/api/services/input_text/set_value"
    method: POST
    headers:
      Authorization: "Bearer {{ hearthminion_homeassistant_auth_token }}"
      Content-type: "application/json"
    body: "{{ json_data | to_json }}"
    validate_certs: false
    body_format: json
    status_code:
      - 200
      - 201
  loop: "{{ hearthminion_hue_lights }}"
  become: false
  delegate_to: localhost
  vars:
    homeassistant_host: "{{ hearthminion_hue_ha_host | default(groups['homeassistant'][0]) }}:8123"
    json_data:
      entity_id: "{{ item.ha_entity }}"
      value: "{{ item.id }}"
  when:
    - hearthminion_hue_lights is truthy
    - item.ha_entity is defined
    - groups['homeassistant'] is defined
  tags:
    - hue
    - hue-homeassistant
