---
# ==================================================================================================
#
# Use API v1 since API v2 does not allow adding lights by serial number.
#
# ==================================================================================================
- name: "Add Hue Lights."
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/{{ hearthminion_hue_username }}/lights"
    method: POST
    body: "{{ item.serial_number | to_json }}"
    ca_path: "hue.crt"
    validate_certs: false
    body_format: json
  loop: "{{ hearthminion_hue_lights }}"
  delegate_to: localhost
  become: no
  when:
    - hearthminion_hue_lights is truthy
    - item.serial_number is defined
    - item.serial_number is truthy
    - item.id is not defined

- name: "Update Hue Lights."
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/clip/v2/resource/light/{{ item.id }}"
    method: PUT
    headers:
      hue-application-key: "{{ hearthminion_hue_username }}"
    body: "{{ item.light_definition | to_json }}"
    ca_path: "hue.crt"
    validate_certs: false
    body_format: json
  loop: "{{ hearthminion_hue_lights }}"
  when:
    - hearthminion_hue_lights is truthy
    - item.light_definition is defined
    - item.id is defined
  delegate_to: localhost
  become: no

- name: "Update Home Assistant Light Entity IDs."
  ansible.builtin.uri:
    url: "http://{{ homeassistant_host }}/api/services/input_text/set_value"
    method: POST
    headers:
      Authorization: "Bearer {{ hearthminion_homeassistant_auth_token }}"
      Content-type: "application/json"
    body: "{{ json_data | to_json }}"
    validate_certs: false
    body_format: json
    status_code:
      - 200
      - 201
  loop: "{{ hearthminion_hue_lights }}"
  vars:
    homeassistant_host: "{{ hearthminion_hue_ha_host | default(groups['homeassistant'][0]) }}:8123"
    json_data:
      entity_id: "{{ item.ha_entity }}"
      value: "{{ item.id }}"
  when:
    - hearthminion_hue_lights is truthy
    - item.ha_entity is defined
    - groups['homeassistant'] is defined
  delegate_to: localhost
  become: no
