---
# tasks file for fortune
- name: Include OS-specific variables.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_network_os | default(none) }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_distribution.split(' ')[0] | lower }}.yml"
        - "{{ ansible_os_family | lower }}_family.yml"
        - "{{ ansible_system | lower }}.yml"
        - main.yml
      paths:
        - "vars"
  become: no
  tags:
    - fortune
    - fortune_debug
    - fortune-debug

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  become: yes
  tags:
    - fortune
    - fortune_debug
    - fortune-debug
    - install-packages

- name: "Install additional fortunes"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ fortunes_dir }}/hearthminion-{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ fortunes }}"
  become: yes
  tags:
    - fortune
    - fortune_debug
    - fortune-debug

- name: "Convert fortunes to fortune dat file."
  command:
    cmd: "strfile hearthminion-{{ item }}"
    chdir: "{{ fortunes_dir }}"
    creates: "{{ fortunes_dir }}/hearthminion-{{ item }}.dat"
  loop: "{{ fortunes }}"
  become: yes
  tags:
    - fortune
    - fortune_debug
    - fortune-debug

