---
# tasks file for fortune
# ==================================================================================================
#
# Add OS-Specific variable files.
#
# Variables:
#   - __os_variables_files: a list, defined in roles/config_defaults/defaults/main.yml
#
# ==================================================================================================
- name: Include OS-specific variables.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ __os_variables_files }}"
      paths:
        - "vars"
  become: no

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  become: yes

- name: "Install additional fortunes"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ fortunes_dir }}/hearthminion-{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ fortunes }}"
  become: yes

- name: "Convert fortunes to fortune dat file."
  ansible.builtin.command:
    cmd: "strfile hearthminion-{{ item }}"
    chdir: "{{ fortunes_dir }}"
    creates: "{{ fortunes_dir }}/hearthminion-{{ item }}.dat"
  loop: "{{ fortunes }}"
  become: yes
