# - hosts: hue_hubs
#   gather_facts: no
#   roles:
#     - role: hearthminion.hearthminion.philips_hue_register

# - hosts: sensehat
#   roles:
#     - role: hearthminion.hearthminion.sensehat

# - hosts: mqtt

# - hosts: bluetooth

# - hosts: owntracks

# - hosts: openzwave

# - hosts: almond

# - hosts: ada

# - hosts:

- hosts: homeassistant
  roles:
    - role: hearthminion.hearthminion.homeassistant
      tags:
        - homeassistant
