# - hosts: sensehat
#   roles:
#     - role: hearthminion.hearthminion.sensehat

# - hosts: mqtt

# - hosts: bluetooth

# - hosts: owntracks

# - hosts: almond

# - hosts: ada

# - hosts:
- hosts: hue_hubs
  gather_facts: false
  roles:
    - role: hearthminion.hearthminion.hue

- hosts: homeassistant
  roles:
    - role: hearthminion.hearthminion.homeassistant
      tags:
        - homeassistant

- hosts: zwavecontrollers
  roles:
    - role: hearthminion.hearthminion.zwavejs2mqtt
      tags:
        - zwavejs2mqtt
