- hosts: mythtv_backend
  roles:
    - role: hearthminion.hearthminion.makemkv
      tags:
        - makemkv

- hosts: mythtv_frontend:mythtv_backend
  roles:
    - role: hearthminion.hearthminion.mythtv
      tags:
        - mythbackend
        - mythfrontend
