- hosts: mythbackend
  roles:
    - role: hearthminion.hearthminion.mythtv_backend
      tags:
        - mythbackend
    - role: hearthminion.hearthminion.makemkv
      tags:
        - makemkv

- hosts: mythfrontend
  roles:
    - role: hearthminion.hearthminion.mythtv_frontend
      tags:
        - mythfrontend
