---
# tasks file for sensehat
# ======================================================================
#
# Task "Install Common Apps"
#
# Installs a set of common apps for all systems on the network
#
# ======================================================================
- name: Prepare Dependencies
  pip:
    name: "{{ pip_packages }}"
    executable: '/usr/bin/pip3'
  become: yes
  #when: ansible_distribution == 'Ubuntu'

# ======================================================================
#
#
#
# TODO: Must be a raspberry pi
#
# ======================================================================
- name: Install sensehat client script
  template:
    src: "sensehat_client.py.j2"
    dest: "/usr/local/bin/sensehat_client.py"
    owner: root
    group: root
    mode: '0755'
  become: yes
  #when: ansible_facts['os_family'] == "Debian"

# ======================================================================
#
#
#
# TODO: Must be a raspberry pi
#
# ======================================================================
- name: Install sensehat client service
  template:
    src: "sensehat_client.service.j2"
    dest: /etc/systemd/system/sensehat_client.service
    owner: root
    group: root
    mode: '0644'
  become: yes

# ======================================================================
#
# Enable Sensehat Service
#
# ======================================================================
- name: Enable Sensehat Service
  shell:
    "{{ item }}"
  with_items:
    - "systemctl enable sensehat_client.service"
    - "systemctl start sensehat_client.service"
  become: yes
