---
# tasks file for mythtv
# ======================================================================
#
# Tasks:
#  
#
# ======================================================================
- name: "Pre-tasks"
  block:
    - name: Include OS-specific variables.
      include_vars: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files: "{{ __os_variables_files }}"
          paths:
            - "vars"
      become: no
      tags:
        - mythtv_backend
        - mythtv-backend
        - mythtv_backend_debug
        - mythtv-backend-debug
        - install-packages

- name: "Include MythTV Backend Tasks."
  include_tasks: mythtv_backend.yml
  when:
    - inventory_hostname in groups['mythtv_backend']

- name: "Include MythTV Frontend Tasks."
  include_tasks: mythtv_frontend.yml
  when:
    - inventory_hostname in groups['mythtv_frontend']

- name: "Ensure we have a password for the mythtv database user"
  ansible.builtin.set_fact:
    mythtv_db_password: "{{ lookup('community.general.passwordstore', __password_lookup) }}"
  vars:
    __password_store_id: "{{ hearthminion_passdb }}/{{ hearthminion_domain }}/services/mysql/{{ hearthminion_mythtv_db_user }}"
    __password_length: "length={{ hearthminion_password_length }}"
    __password_overwrite: "overwrite={{ hearthminion_overwrite_password }} backup=yes"
    __password_create: "create=true"
    __password_symbols: "nosymbols=true"
    __password_lookup: "{{ __password_store_id }} {{ __password_create }} {{ __password_length }} {{ __password_symbols }} {{ __password_overwrite }}"
  when:
    - hearthminion_mythtv_db_password == "password"

- name: "Install config file"
  ansible.builtin.template:
    src: "config_xml.j2"
    dest: "/etc/mythtv/config.xml"
    owner: "root"
    group: "root"
    mode: "0644"
  become: yes
  tags:
        - mythtv_backend
        - mythtv-backend
        - mythtv-frontend
        - mythtv_frontend
        - mythtv

- name: "Update MythTV Database."
  include_tasks: mythtv_database.yml
  
